In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#Loading data and assigning variables

data = np.loadtxt("ex1data2.txt", comments="#", delimiter=",")
y = np.array([data[:, 2]]).T
m = np.size(y)
X = np.c_[ data[:, 0], data[:,1] ]
theta = np.zeros((3,1))

In [3]:
# Feature Normalization
mu = np.mean(X, axis=0)
sigma = np.std(X, axis=0)

norm_X = np.divide((X - mu),sigma)

X = np.c_[np.ones(m), norm_X[:,0], norm_X[:,1] ]

In [4]:
# Cost Function

def costFunction(theta):
    hypothesis = np.dot(X,theta)
    squaredError = (hypothesis - y)**2
    sumSquaredError = np.sum(squaredError)
    J = 1/(2*m) * sumSquaredError
    return(J)

print(costFunction(theta))

65591548106.45744


In [5]:
# Gradient Descent

iterations = 1500
alpha = 0.1
for i in range(iterations):
    
    beta = np.dot(X,theta)
    delta = (1/m) * np.dot((beta - y).T, X)
    theta = theta - (alpha * delta.T)
    
theta

array([[340412.65957447],
       [109447.79646964],
       [ -6578.35485416]])

In [6]:
# Using our algorithm
def predictionFunction(squareFt, size):
    prediction = np.dot([1, (squareFt-mu[0])/sigma[0], (size-mu[1])/sigma[1]], theta)
    return (np.ndarray.item(prediction))

predictionFunction(1650,3)

array([293081.4643349])

In [7]:
# Using the Normal Equation
theta = 0

theta = np.dot(np.dot(np.linalg.pinv(np.dot(X.T, X)), X.T),y)
theta

array([[340412.65957447],
       [109447.79646964],
       [ -6578.35485416]])

In [8]:
predictionFunction(1650, 3)

array([293081.4643349])

In [ ]:
# Now we know how much our house could sell for! :)